/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vm.project;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author usuario
 */
public class Interphase extends javax.swing.JFrame
{
   translate vmCode;
   String fileName="";

   /**
    * Creates new form Interphase
    */
   public Interphase()
   {
      initComponents();
       Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
      this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jPanel1 = new javax.swing.JPanel();
      jScrollPane2 = new javax.swing.JScrollPane();
      txtHack = new javax.swing.JTextArea();
      btnImport = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();
      btnExport = new javax.swing.JButton();
      jLabel3 = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      txtVm = new javax.swing.JTextArea();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setBackground(new java.awt.Color(204, 204, 204));

      jPanel1.setBackground(new java.awt.Color(0, 102, 153));

      txtHack.setColumns(20);
      txtHack.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
      txtHack.setRows(5);
      txtHack.setDisabledTextColor(new java.awt.Color(0, 0, 153));
      txtHack.setEnabled(false);
      jScrollPane2.setViewportView(txtHack);

      btnImport.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
      btnImport.setText("Import");
      btnImport.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            btnImportActionPerformed(evt);
         }
      });

      jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(255, 255, 255));
      jLabel1.setText("Hack code");

      btnExport.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
      btnExport.setText("Export");
      btnExport.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            btnExportActionPerformed(evt);
         }
      });

      jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(255, 255, 255));
      jLabel3.setText("Virtual machine code");

      txtVm.setColumns(20);
      txtVm.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
      txtVm.setRows(5);
      txtVm.setDisabledTextColor(new java.awt.Color(0, 0, 153));
      txtVm.setEnabled(false);
      jScrollPane1.setViewportView(txtVm);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 1466, Short.MAX_VALUE)
         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
               .addGap(155, 155, 155)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                     .addComponent(jLabel3)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btnImport))
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(258, 258, 258)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                     .addComponent(jLabel1)
                     .addGap(289, 289, 289)
                     .addComponent(btnExport))
                  .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap(172, Short.MAX_VALUE)))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 791, Short.MAX_VALUE)
         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
               .addGap(104, 104, 104)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel1)
                     .addComponent(btnExport)
                     .addComponent(btnImport)))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                  .addComponent(jScrollPane2))
               .addContainerGap(42, Short.MAX_VALUE)))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnImportActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnImportActionPerformed
   {//GEN-HEADEREND:event_btnImportActionPerformed
      // TODO add your handling code here:
      try
      {
         //front-end
         JFileChooser chooser = new JFileChooser();
         chooser.setFileFilter(new FileNameExtensionFilter("*.vm","vm"));
         chooser.setAcceptAllFileFilterUsed(false);

         chooser.setCurrentDirectory(new java.io.File(".//..//..//archi_project//nand2tetris//projects//07"));
         chooser.showOpenDialog(chooser);

         String path = chooser.getSelectedFile().getAbsolutePath();
         fileName = path.replace("\\", "!").split("!")[path.replace("\\", "!").split("!").length-1];

            //back-end
            vmCode = new translate(path);

            //front-end
            txtVm.setText(vmCode.vmCodeContent);

            txtHack.setText(vmCode.translateToHack());

         }catch(Exception e)
         {

         }
   }//GEN-LAST:event_btnImportActionPerformed

   private void btnExportActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExportActionPerformed
   {//GEN-HEADEREND:event_btnExportActionPerformed
      // TODO add your handling code here:
      if(!txtHack.getText().isEmpty())
      {
         int count =1;
         File export;
         JFileChooser chooser = new JFileChooser();
         chooser.setCurrentDirectory(new java.io.File("."));
         chooser.setDialogTitle("Choose a location to save this Hack");
         chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
         chooser.setAcceptAllFileFilterUsed(false);
         String name = "\\"+fileName+".asm";
         //
         try
         {
            if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
            {
               if((export = new File(chooser.getCurrentDirectory()+name)).exists())
               {
                  name = "\\"+fileName+"("+count+").asm";
                  while((export = new File(chooser.getCurrentDirectory()+name)).exists())
                  {
                     count++;
                     name = "\\"+fileName+"("+count+").asm";
                  }
               }
               PrintWriter writer = new PrintWriter(export, "UTF-8");
               String[] lines = txtHack.getText().split("\n");
               for (int i = 0; i < lines.length; i++)
               {
                  writer.println(lines[i]);
               }
               writer.close();
               JOptionPane.showMessageDialog(null,"¡Export success!");
            }
         }catch(Exception e)
         {
         }
   }//GEN-LAST:event_btnExportActionPerformed

   }// </editor-fold>                        

   /**
    * @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(Interphase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(Interphase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(Interphase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(Interphase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
        //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new Interphase().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnExport;
   private javax.swing.JButton btnImport;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JTextArea txtHack;
   private javax.swing.JTextArea txtVm;
   // End of variables declaration//GEN-END:variables
}
